### ISSUE TITLE
Put Blog Post URL in the link of the button in email content automatically

### ISSUE THREAD

**Issue by coa0329** [coa0329/Bhaang#24]
Put Blog Post URL in the link of the button in email content automatically

**Comment by daver78** [comment]
@paagla123 and @coa0329 Yes this is a must.  Be aware that at some point soon, we will also need to:

a) Append a UTM string to the `<a href>`.  

(I'm not sure where the team is relative to getting Google Analytics figured out in order to track conversions, but I believe the UTM string is going to play a part in this.)

b) In future, we may need to pass additional vars in query string format.  

I raise this so that you consider it when you code it.  Give yourself room for this.

**Comment by paweenwich** [comment]
using Block Post URL is done.

**Comment by paagla123** [comment]
This is working fine.
