### ISSUE TITLE
List of forms and associated fields

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#36]

**Comment by paagla123** [comment]
@AumpaiFung please check
https://docs.google.com/a/mindfiremail.info/spreadsheets/d/1M6-F7dKyllwu1xCLYoxjZFnqFoacCgo_muQ3enH0JN8/edit?usp=sharing

**Comment by AumpaiFung** [comment]
Updated task: 
- Form Library Page [Done]
- Form Builder Page (with textbox ONLY)
     - Create New Form [Done]
     - Edit New Form [Done]
     - Save HTML of form to DB [Done]

**Comment by daver78** [comment]
Thank you @AumpaiFung.  @paagla123 Will check today.

**Comment by paagla123** [comment]
@AumpaiFung very good start. Please note the following changes:
1) Please make State and Country drop down fields. The list is available at GitHub\Bhaang\httpdoc\State_and_Country.html . 
2) You missed zip in all the form fields. Every one of them should have zip.
3) I have updated the Google Doc pl see.
4) Pl make sure you have form tags, method=post and submit button in the htmls

**Comment by AumpaiFung** [comment]
@paagla123  
1. State & Country dropdown is done.
2. Done.
3. On process.
4. Done.
5. Done.
6. Done.

**Comment by AumpaiFung** [comment]
@paagla123 
Question: 
What is submission?  On Form Library List page.

**Comment by daver78** [comment]
@AumpaiFung For marketers, it is important to know how well a form converts.  By convert, we mean the following:

**Form A** has received 100 visitors, and 5 have submitted the form.  That's a 5% conversion rate.

**Form B** has received 100 visitors, and 40 have submitted the form.  That's a 40% conversion rate, which is statistically significant.  The marketer would likely chose to use Form B going forward (and if she's smart, would create a Form C and see if she can beat 40%).

In order to eventually compute these values and provide the User with this insight, we need to track how many people "see" and "submit" each form.  I haven't thought about the way to accomplish this technically, but I'm sure you / @paagla123  / @paweenwich can come up with a way :)

**Comment by AumpaiFung** [comment]
@paagla123   
I added input type datetime to project. 
The known bug was on the right block of form page. 
The calendar icon can not popup datetime schedule for now. 
Please take a look.

And @daver78 
I found that popup modal size (Setting button of each field) on form page, it's smaller than before.
I'm not sure that it's your intention or not. 
The style.css file was updated, then I'm not correct it.

**Comment by daver78** [comment]
@AumpaiFung I see that the modal is skinny now.  That's odd, I don't believe I touched `style.css` in this regard.  I think we can live with it for now, right @paagla123?

**Comment by paagla123** [comment]
@AumpaiFung can you please provide an update here? I believe there are still a lot of things to finish here.  I have updated the Google Doc - please match with it. Also - I provided code for drop down of country. That is also missing.

**Comment by paagla123** [comment]
@AumpaiFung Available for Trade In should have a drop down with Yes / No values.

**Comment by AumpaiFung** [comment]
All selectbox is done. 
Datetime icon on form library still can not popup date scheduler (Known bug). 
But on ebook setup landing page can do. 

Please take a look.

**Comment by paagla123** [comment]
@AumpaiFung please add an email in the Celebrate A Day template. That was my mistake to miss it.
