### ISSUE TITLE
daVinci Login Screen

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#60]
Please use the login screen Dave put together @ https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php?page=login

**Comment by paagla123** [comment]
Hi @paweenwich , are we planning to put this into the login screen at davinci.mindfireinc.com? Thx

**Comment by daver78** [comment]
@paagla123 and @paweenwich When you go to dv.mindfireinc.com, there is a link to login.  The login page should load using the above treatment.

Let me know when it is ready and I will link to it from the website.

**Comment by paagla123** [comment]
Yes - but when you log in, its going to the wrong place. Going to https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php?page=homePage , whereas it should go to http://davinci.mindfireinc.com/admin/welcome.php . Also @daver78 , we should add a select account drop down to the login screen - see the one from https://web2xmm.com/admin/login.html

**Comment by coa0329** [comment]
Done.

Only the login part works.

**Comment by daver78** [comment]
@paagla123 I confirm the login page is there and I can access it from dv.mindfireinc.com.

However, I did not check "forgot password".  Can you check that?  I wonder about the branding and messaging in the email, etc.

**Comment by paagla123** [comment]
The login screen works thank you. 
@coa0329 we need to adjust a couple of things.
1) The drop down for the accounts should be sorted by account name.
2) Once logged in, please redirect to http://davinci.mindfireinc.com/admin/welcome.php (no SSL - pl NOTE) instead of https://web2xmm.com/admin/welcome.php
3) Forgot password provides a nice pop-up - but I did not get any email. No need to change this one before PRINT17 right now - we can do this later on.

**Comment by coa0329** [comment]
1 The drop down for the accounts should be sorted by account name.
- Fixed

2 Once logged in, please redirect to http://davinci.mindfireinc.com/admin/welcome.php (no SSL - pl NOTE) instead of https://web2xmm.com/admin/welcome.php
- You must login from http://davinci.mindfireinc.com/admin/login.html

3 Forgot password provides a nice pop-up - but I did not get any email. No need to change this one before PRINT17 right now - we can do this later on.
- Please be careful when you click forget password. It will reset the password like you click forget password in studio. We use the same api.

**Comment by daver78** [comment]
@coa0329 I think there is an action here for me to make the website's login page point to `http://davinci.mindfireinc.com/admin/login.html`.  I will create myself a task and do it.

**Comment by paagla123** [comment]
All of these are working well. I am closing it. I will open a new one re changing temporary pwd created by pwd reset. Thx
