### ISSUE TITLE
My Campaigns display is NOT by most recent edited

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#62]
Its because the my campaign display (or the display of recent campaigns on home page) goes by the time on the user's local machine and does not account for the time zone. It should either account for the time zone or use soe sort of server timestamp. Se screenshot below. Mine was @ 726AM PST which is after 1802 BKK time, but went below because of not using time zone. Pl fix this.

![image](https://user-images.githubusercontent.com/29718335/29974491-debc4bc8-8ee7-11e7-9cea-1426b47945d8.png)

**Comment by paweenwich** [comment]
Done (By adding time zone (GMT) to lastEditDate field)   Previously, there is no time zone.

**Comment by daver78** [comment]
@paweenwich I have a feeling we need to edit the UI too.  As mentioned in my UI update note, I changed the UI to use `<time am-time-ago="item.lastEditDate">`.  I believe it uses the User's timezone, which is why I see:

![image](https://user-images.githubusercontent.com/7561473/30030786-b572cd6a-9143-11e7-9b67-be96c0c55c63.png)

And where did you add the timezone?  In DB I see this:

![image](https://user-images.githubusercontent.com/7561473/30030867-f2e7f01c-9143-11e7-94dc-514b9767d78a.png)

Will it show up here after User makes the next edit?

**Comment by paagla123** [comment]
FIXED Closing
