### ISSUE TITLE
Summary of Dave's UI Love for 9/3/17

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#64]
All the following were made directly to "production."  Please backup before overwriting.

**Updates to welcome.php**:
- Updated jumbotron
- Updated little green “LIVE” indicators using ternary // e.g.: `{{item.status==‘Edit’ ? ‘LIVE’ : ‘DRAFT’}}`, but this is probably a hack.  We should address in the controller (not in the UI), right?
- Added a search feature
- Added a “Modified <moments ago>” feature using `angular-moment`
- Added header to campaign table
- Formatted reach/people with `|number`
- Updated "PromoteBlogPost" to "Promote a Blog Post" and "PromoteEbook" to "Promote an eBook", again using `ternary` but as I mentioned above, this is a hack.  We should probably do it elsewhere, right?

**Updates to leftWrapper.php**:
- Commented out “Campaigns”; I don’t think we need it if they’re listed on the “Home” page.  Agree, disagree @paagla123?

**Updates to topWrapper.php**:
- Commented out search until we have site wide DV search
- Modified `<span class="m-r-sm text-muted welcome-message">Hi userName, you're logged in to <?php echo $accountName;?><span>` … but need `userName` var. @paweenwich or @coa0329, what is the right value?  I didn't look deeply yet.

**Updates to header.php**:
- Updated page `title`
- Added `<link rel="icon" href="https://s3.amazonaws.com/mindfiredavinci/img/DV-logo.png" type="image/x-icon" />`

**Updates to pickBlueprint.php**:
- Fixed broken images, and moved all to S3
- Changed `<h1>` at top
- Changed `modal` for Promote a Blog Post.  If it is better we should apply same idea to eBook and rest

**Comment by paweenwich** [comment]
Thank @daver78

**Comment by daver78** [comment]
@paweenwich You're welcome.  I left a question for you above in the change-log.  Can you let me know?

**Comment by paweenwich** [comment]
the variable name for "username" is $email (the one that user login).  It is defined in logincredential.php along with a few others variable.    I did take are of that.

**Comment by paweenwich** [comment]
@daver78 You need to make direct change at server for a while.  The main problem is couchDB.   because couchDB run on another port and we need to access it from Java script..   To avoid CORS (Cross site scripting)  we config apache to create virtual /couchdb to redirect to traffic to couchdb.  If codeanyway can do the same, then it would be much easier to setup.  if not we need to make php page to do the trick.  ( I have tried setting the CouchDB for CORS support.  However, somehow, it does not work as manual indicate.)

**Comment by daver78** [comment]
@paweenwich I had a feeling it was something like this.  Did you try modifying apache on codeanywhere?  It should be possible.

If you tell me what to change, I will try it.

**Comment by daver78** [comment]
There are still a few open issues from my UI updates above:

* @paweenwich Thank you for `$email`.  I was looking for the user's first name and last name.  Do we store that anywhere?  If not, we will use `$email` for now.

* @paagla123 I commented out “Campaigns”; I don’t think we need it if they’re listed on the “Home” page. Agree, disagree

@paweenwich When I updated the little green “LIVE” indicators, I used ternary like `{{item.status==‘Edit’ ? ‘LIVE’ : ‘DRAFT’}}`, but this is probably a hack. We should address in the controller (not in the UI), right?

**Comment by paagla123** [comment]
@daver78 I would personally prefer having Campaign in the left tab because of two reasons:
1) Its more intuitive for many users
2) Ideally Home should have only the most recently used N number of campaigns.
I also would recommend leaving the SEARCH on there - even if it does not work. Any objections to that?

**Comment by daver78** [comment]
@paagla123 OK, I can:

* make "Home" reflect the most recently modified 5 Campaigns.  Does that make sense to you?
* uncomment "Campaigns" from left-nav
* apply UI-love to "Campaigns" page

Regarding SEARCH at top of all pages, my rationale is mostly around demoing at Print 17.  

No matter how many times we tell the involved team that certain things don't work, I know from experience that people will forget and I will be bombarded with "_Hey, did you know that such-and-such doesn't work?_" or "_When I click on this, nothing happens_."

If it were just you and me doing the demos, it would be fine.  But given that we are opening it up to others, I think we run the risk of making ourselves look less polished since not all team members are as intimate with DV as you and I are.

Thoughts?

**Comment by paagla123** [comment]
I was thinking the same thing about having placeholder features. We can hide them if you think it will keep things cleaner.

**Comment by paweenwich** [comment]
@daver78  Basically, we need to add these 
   ProxyPass /couchdb http://www.web2xmm.com:5984/
   ProxyPassReverse /couchdb http://www.web2xmm.com:5984/

I think, I need a root to modify the apache2.  If you can do that it will help a lot.  :)

**Comment by paweenwich** [comment]
@daver78  I will create an issue on user's firstname lastname.

**Comment by daver78** [comment]
@paweenwich OK, I created a `dave.conf` in `/etc/apache2/sites-available` which contains:

```
<Virtualhost *>
  DocumentRoot "/home/cabox/workspace/html/admin"
  ServerName localhost
  ServerAdmin support@mycompany.com
  DirectoryIndex welcome.php index.php ProxyRequests On
  ProxyPreserveHost On
  ProxyVia full

  <proxy>
    Order deny,allow
    Allow from all
  </proxy>

ProxyPass /couchdb http://www.web2xmm.com:5984/
ProxyPassReverse /couchdb htp://www.web2xmm.com:5984/

</Virtualhost>
```

... but this page [](http://da-vinci-core-daver438618.codeanyapp.com/html/admin/login.html) still doesn't work.  I'll continue to debug, but let me know if you see anything fishy with what I pasted above.

**Comment by daver78** [comment]
@paweenwich By the way, if you want to access my machine on codeanywhere, you can do `sudo su -` and will get `root`.

**Comment by paweenwich** [comment]
@daver78 I am not sure that the ProxyPass work.  Because if it work when we use /couchdb  it  access to couchdb.  For example,  https://www.web2xmm.com/couchdb/db228  will return you json something.  However,  http://da-vinci-core-daver438618.codeanyapp.com/couchdb or http://da-vinci-core-daver438618.codeanyapp.com/html/couchdb or daver438618.codeanyapp.com/html/admin/couchdb  all return error (no page found).   

First, we need to make sure that mod_proxy is enabled.  Then finding why the ProxyPass is not work.  

By the way, 
ProxyPassReverse /couchdb htp://www.web2xmm.com:5984/
should be 
ProxyPassReverse /couchdb http://www.web2xmm.com:5984/

(t missing)
But I don't think this is the case.   I will checking this again tomorrow.

**Comment by daver78** [comment]
@paweenwich OK, that makes sense.  I will likely not be able to get into this today.

However, did you check Docker?  I suggested to @paagla123 that you become familiar with Docker, as I believe if we "dockerize" Da Vinci, these problems (and more) will evaporate.  

I think it would be a good idea to speed up development and eventually, to make deployment very easy and stress-free.

**Comment by daver78** [comment]
Closing for now.  Comment for @paweenwich in issue #74.
