### ISSUE TITLE
[Promote a Blog Post] Give love to Edit Email UI

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#75]

**Comment by daver78** [comment]
@paweenwich, I updated `editPromoteBlog.php` as follows.  Can you tag the person who is working in this area so that they know?

- Used `angular-chosen` ([http://leocaseiro.github.io/angular-chosen/#ngoptions-and-ngmodel](http://leocaseiro.github.io/angular-chosen/#ngoptions-and-ngmodel)) to try and give a little extra love to UI
- Applied `angular-chosen` to FROM, TEMPLATE, and SEND TEST.  If I broke anything, you can revert back to old (I commented the previous code out)
- Revised help text at top
- Made numerous small html fixes/updates

@paagla123  and @paweenwich, there's a known issue with the width of the `select` using `angular-chosen`.  Does it look OK on your monitor, or does it extend beyond the right border?

**Comment by daver78** [comment]
@paagla123 If you and @paweenwich are OK with the love applied to Email #1, the same changes need to be applied to Email #2, #3, and so on.  Before we do that let's make sure we are OK with it.

**Comment by daver78** [comment]
@paagla123 and @paweenwich Did you discuss this?  We need to apply the treatment I did to Email #1 to the rest.  Would prefer the team do this for me if possible.

**Comment by paagla123** [comment]
@paweenwich I do not believe this has been done. Can you please assign someone? Thx

**Comment by paagla123** [comment]
@daver78 @paweenwich @coa0329 related issues are #53, #54 and #77

**Comment by jiewsone** [comment]
I already change all emails UI as same as Email1.

**Comment by daver78** [comment]
@jiewsone thank you.

@paweenwich Forgive me as I have not had a chance to look at the code yet, but I think for maintainability, we should consider some sort of angular template or `ng-repeat` situation for the three email UI portion. 

If I recall, we have them separately coded in the HTML (which is what I did in my mockup), but that was just for quick and dirty purposes.

What do you think?  Should we add this to the list of things to possibly refactor?

**Comment by paagla123** [comment]
All are same in staging

**Comment by paweenwich** [comment]
@daver78 You are correct.  There are a lot of thing that can be refactor, to make in maintainable.  I saw your refactor issue.  Why don't we prioritize things and put the list there.

**Comment by jiewsone** [comment]
I already refactor the email tab code.

**Comment by daver78** [comment]
@jiewsone Yes, I noticed that you had started this.  Did you finish?
