### ISSUE TITLE
Where can I edit each Blueprint's default content?

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#76]
I would like to update the default text.  Where is it located?  I have not looked in detail.

**Comment by paweenwich** [comment]
@daver78  For the default value, we keep in db at /master/Default_PromoteBlog   

http://web2xmm.com:5984/_utils/document.html?master/Default_PromoteBlog

For blueprint info 

http://web2xmm.com:5984/_utils/document.html?master/templates

**Comment by daver78** [comment]
@paweenwich Makes sense.  If I edit the info in the `JSON`, and click "SAVE" -- that's all I need to do, correct?

Is it possible that anyone else will overwrite me?  Should I keep a copy of the `JSON` once I've modified it, just in case?

**Comment by paweenwich** [comment]
Yes, that all you need, click "SAVE".  However, according to my understanding, basically, all documents in couchDB have revision number "_rev".  You can update the document if and only if the document contain current _rev value.    For example, suppose right now _rev = 12-xxxx.    You and I open document at the same time.   We both get _rev=12-xxxx in our document .  If you do "Save document" first, then the current _rev will be 13-xxxx.   This will prevent me, which still has _rev = 12-xxxx  from overwrite yours.   So, I can not save it.  I need to refresh/reload to get the correct _rev value in order to save it.    If you can save it, no one can overwrite yours without seeing your stuff first.

**Comment by daver78** [comment]
@paweenwich OK that makes sense.  I'm going to close this issue now.
