### ISSUE TITLE
Refactoring Backlog

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#97]
Here's a backlog list of items we should consider for refactor:

- Externalize our angular to `app.js` instead of inline.

- We use `php include`, `w3-include-html`, and `$routeProvider templateURL`.  We should pick one method and stick with it.  My preference would be to standardize with the `angular` way.

- In many areas of the UI, we copy-n-paste HTML snippets (like in Promote a Blog Post when we edit the Emails).  I did this in my mockup for quick and dirty.  Instead, I think we should consolidate into a directive, template, or something else for better maintainability. DAVE RECOMMENDS: Use custom angular directive : https://docs.angularjs.org/guide/directive

- `{{}}` within the MAML were mentioned by @paweenwich to be confusing and difficult to remember.  Is there an easier way to refactor this?
  
- Instead of multiple PHP, I think we should consider using `$routeProvider` to create a SPA.  

- Do we want to use both `PHP` and `JS` as our backend service layer?  Should we pick one or the other?  Not sure it really matters but right now stuff is written in both.

- Unit Tests with something like Karma, Jasmine, etc.  Each developer should write their own and eventually we move to TDD.

- Set up CICD with Git and our tests to deploy daily, hourly, if/when needed

- Be ready to minify our js.  For example, make sure our app.controllers are like:

```
app.controller(“something”, [“$scope”, function(c) {
c.name = “whatever”;
}]);

```
instead of:

```
app.controller(“something", function ($scope){
$scope.name = “whatever”;
});

```
Since in the second example, we'd get screwed because `$scope` could be changed to something like `c`, and `c.name = "whatever"` will not work when used like `{{name}}`.

**Comment by daver78** [comment]
@paweenwich and @paagla123 Can you look at the list above and tell me if you think anything is missing?  I'm sure you've run across a few things too.

**Comment by paweenwich** [comment]
@daver78 I think  "php include"  comparable to  "w3-include-html".  Both are static include which right now we are using it to include top, left and buttom part.    We can get ride of both if we decide to go with SPA.  

So, the problem is are we going to SPA or not.  I never do any SPA before, so I am qualify to decide on this.   For me, MPA has benefit in resetting Browser/Javascript stage every time when new page is loaded   So, any Javascript bug is contain to that particular page only.  While, in SPA, it will spread all over and make much more difficult to identify and fix.    For multiple developer which are not quite strong on JavaScript (like us), I think MPA is safer path.

**Comment by daver78** [comment]
@paweenwich OK, I am fine with MPA for now.  

However, I notice that some of our developers are using `$routeProvider` already in some areas, so we are like hybrid SPA-MPA?

Let me know if you're OK with that.  I'm fine with it for now.

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#51
